# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-30 11:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Databasemessage',
            fields=[
                ('db_tableid', models.AutoField(primary_key=True, serialize=False)),
                ('db_title', models.CharField(max_length=60)),
                ('db_database', models.CharField(max_length=60)),
                ('db_table', models.CharField(max_length=60)),
                ('db_auth', models.CharField(max_length=60)),
                ('db_tableenvname', models.CharField(max_length=100)),
                ('db_ctime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Dbmessage',
            fields=[
                ('db_id', models.AutoField(primary_key=True, serialize=False)),
                ('db_title', models.CharField(max_length=60, verbose_name='\u5b9e\u4f8b\u540d')),
                ('db_type', models.CharField(max_length=60, verbose_name='\u6570\u636e\u5e93\u7c7b\u578b')),
                ('db_ip', models.GenericIPAddressField()),
                ('db_port', models.IntegerField()),
                ('db_user', models.CharField(max_length=60)),
                ('db_passwd', models.CharField(max_length=60)),
                ('db_envname', models.CharField(max_length=100, verbose_name='\u5b9e\u4f8b\u4fe1\u606f')),
                ('db_ctime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Querymessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qu_dbid', models.IntegerField()),
                ('qu_uname', models.CharField(max_length=60)),
                ('qu_dbtitle', models.CharField(max_length=60)),
                ('qu_tableid', models.IntegerField()),
                ('qu_state', models.CharField(default='guest', editable=False, max_length=10)),
                ('qu_ctime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
