# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-30 12:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('query', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='querymessage',
            name='qu_dbtitle',
        ),
        migrations.AlterField(
            model_name='querymessage',
            name='qu_state',
            field=models.CharField(default='guest', max_length=10),
        ),
    ]
