# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-30 12:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('query', '0002_auto_20160830_1210'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='querymessage',
            name='qu_state',
        ),
    ]
