# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-31 14:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('query', '0003_remove_querymessage_qu_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='dbmessage',
            name='db_auth',
            field=models.CharField(max_length=60, null=True),
        ),
    ]
