# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-31 14:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('query', '0004_dbmessage_db_auth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dbmessage',
            name='db_auth',
            field=models.CharField(max_length=60),
        ),
    ]
