# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-31 19:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('query', '0006_auto_20160831_1856'),
    ]

    operations = [
        migrations.AddField(
            model_name='databasemessage',
            name='db_type',
            field=models.CharField(max_length=60, null=True),
        ),
    ]
