# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-31 19:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('query', '0007_databasemessage_db_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='databasemessage',
            name='db_type',
            field=models.CharField(max_length=60),
        ),
    ]
