# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-05 15:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('query', '0008_auto_20160831_1922'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sqlmessage',
            fields=[
                ('sql_id', models.AutoField(primary_key=True, serialize=False)),
                ('sql_user', models.CharField(max_length=60)),
                ('sql_dbtitle', models.CharField(max_length=60)),
                ('sql_dbdataba', models.CharField(max_length=60)),
                ('sql_info', models.CharField(max_length=255)),
                ('sql_ctime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
